# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 50, 701, 491))
        self.widget.setObjectName("widget")
        self._2 = QtWidgets.QGridLayout(self.widget)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setObjectName("_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self._2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setObjectName("label_2")
        self._2.addWidget(self.label_2, 0, 1, 1, 1)
        self.availableAddresseTexBox = QtWidgets.QTextBrowser(self.widget)
        self.availableAddresseTexBox.setObjectName("availableAddresseTexBox")
        self._2.addWidget(self.availableAddresseTexBox, 4, 1, 1, 1)
        self.ipAdressEdit = QtWidgets.QTextEdit(self.widget)
        self.ipAdressEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ipAdressEdit.setFont(font)
        self.ipAdressEdit.setObjectName("ipAdressEdit")
        self._2.addWidget(self.ipAdressEdit, 1, 0, 1, 1)
        self.maskEdit = QtWidgets.QTextEdit(self.widget)
        self.maskEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.maskEdit.setFont(font)
        self.maskEdit.setObjectName("maskEdit")
        self._2.addWidget(self.maskEdit, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4, 4, 0, 1, 1)
        self.adresseCountDisplay = QtWidgets.QLCDNumber(self.widget)
        self.adresseCountDisplay.setMaximumSize(QtCore.QSize(16777215, 40))
        self.adresseCountDisplay.setStyleSheet("color: red;")
        self.adresseCountDisplay.setProperty("intValue", 0)
        self.adresseCountDisplay.setObjectName("adresseCountDisplay")
        self._2.addWidget(self.adresseCountDisplay, 2, 1, 1, 1)
        self.calculatBtn = QtWidgets.QPushButton(self.widget)
        self.calculatBtn.setObjectName("calculatBtn")
        self._2.addWidget(self.calculatBtn, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setObjectName("label_3")
        self._2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self._2.addWidget(self.label_5, 3, 0, 1, 1)
        self.broadcastAddress = QtWidgets.QTextBrowser(self.widget)
        self.broadcastAddress.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.broadcastAddress.setFont(font)
        self.broadcastAddress.setReadOnly(True)
        self.broadcastAddress.setObjectName("broadcastAddress")
        self._2.addWidget(self.broadcastAddress, 3, 1, 1, 1)
        self._2.setRowStretch(0, 1)
        self._2.setRowStretch(1, 1)
        self._2.setRowStretch(2, 1)
        self._2.setRowStretch(3, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Adres IP"))
        self.label_2.setText(_translate("MainWindow", "Maska podsieci"))
        self.label_4.setText(_translate("MainWindow", "Lista dostępnych adresów"))
        self.calculatBtn.setText(_translate("MainWindow", "Oblicz"))
        self.label_3.setText(_translate("MainWindow", "Liczba adresów"))
        self.label_5.setText(_translate("MainWindow", "Adres broadcast"))
        self.broadcastAddress.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cascadia Code\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
